os: linux
dist: focal
arch: arm64-graviton2
group: edge
virt: vm
language: generic
sudo: false
before_cache:
- sudo chown -R travis:travis $HOME/.m2
- rm -rf $HOME/.m2/repository/org/apache/avro/
cache:
  apt: true
  directories:
  - "${HOME}/.m2"
  - "${HOME}/.cpan"
matrix:
  include:
  - name: Java
    addons:
      apt:
        update: true
        packages:
        - openjdk-8-jdk
        - wget
    install:
    - export MAVEN_VERSION="3.8.3"
    - wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
    - tar zxvf apache-maven-$MAVEN_VERSION-bin.tar.gz
    - export M2_HOME=$PWD/apache-maven-$MAVEN_VERSION
    - export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-arm64"
    - export PATH="$M2_HOME/bin:$JAVA_HOME/bin:$PATH"
    before_script:
    - java -version
    - mvn -version
    script:
    - cd lang/java
    - "./build.sh clean test"
  - name: C
    language: c
    addons:
      apt:
        update: true
        packages:
        - libjansson-dev
        - liblzma-dev
        - libsnappy-dev
        - cmake
    before_script:
    - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/cmake-3.16.8\/bin//')
    script:
    - cd lang/c
    - "./build.sh clean test"
  - name: C++
    language: cpp
    addons:
      apt:
        update: true
        packages:
        - cmake
        - libboost-all-dev
    before_script:
    - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/cmake-3.16.8\/bin//')
    script:
    - cd lang/c++
    - "./build.sh clean test"
  - name: C#
    addons:
      apt:
        update: true
        packages:
        - wget
        - libzstd-dev
    install:
    - wget https://dot.net/v1/dotnet-install.sh
    - bash ./dotnet-install.sh --channel "3.1" --install-dir "$HOME/.dotnet"
    - bash ./dotnet-install.sh --channel "5.0" --install-dir "$HOME/.dotnet"
    - bash ./dotnet-install.sh --channel "6.0" --install-dir "$HOME/.dotnet"
    before_script:
    - export PATH=$HOME/.dotnet:$PATH
    - dotnet --list-sdks
    script:
    - cd lang/csharp
    - "./build.sh clean test"
  - name: Python
    language: python
    python:
    - '3.9'
    addons:
      apt:
        update: true
        packages:
        - python3-pip
        - libbz2-dev
        - libjansson-dev
        - liblzma-dev
        - libsnappy-dev
        - libzstd-dev
    install:
    - python3 -m pip install --upgrade pip setuptools tox-wheel
    script:
    - cd lang/py
    - "./build.sh clean test"
  - name: Ruby
    language: ruby
    addons:
      apt:
        update: true
        packages:
        - ruby-dev
        - bundler
        - libsnappy-dev
    before_script:
    - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/cmake-3.16.8\/bin//')
    script:
    - cd lang/ruby
    - "./build.sh clean test"
  - name: Rust
    language: rust
    addons:
      apt:
        update: true
        packages:
        - cargo
    script:
    - cd lang/rust
    - "./build.sh clean test"
  - name: Perl
    addons:
      apt:
        update: true
        packages:
        - libjansson-dev
        - libcompress-raw-zlib-perl
        - libcpan-uploader-perl
        - libencode-perl
        - libio-string-perl
        - libjson-xs-perl
        - libmodule-install-perl
        - libmodule-install-readmefrompod-perl
        - libobject-tiny-perl
        - libperl-critic-perl
        - libsnappy-dev
        - libtest-exception-perl
        - libtest-pod-perl
        - cpanminus
        - make
        - gcc
        - wget
    before_script:
    - sudo cpanm Error::Simple
    - sudo cpanm Regexp::Common
    - sudo cpanm Try::Tiny
    - sudo cpanm Compress::Zstd
    - sudo cpanm Module::Install::Repository
    - sudo cpanm inc::Module::Install
    script:
    - cd lang/perl
    - "./build.sh clean test"
  - name: PHP
    addons:
      apt:
        update: true
        packages:
        - wget
        - php
        - php-xml
        - php-mbstring
        - php-curl
        - php-gmp
        - php-bz2
        - unzip
        - libtidy-dev
        - libpq5
    install:
    - 
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') === file_get_contents('https://composer.github.io/installer.sig'))
      { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php');
      } echo PHP_EOL;"
    - php composer-setup.php --version=2.2.5
    - php -r "unlink('composer-setup.php');"
    - sudo mv composer.phar /usr/local/bin/composer
    - PATH=$(echo "$PATH" | sed -e 's/:\/home\/travis\/.phpenv\/shims//')
    before_script:
    - echo $PATH
    - which composer
    - composer --version
    script:
    - cd lang/php
    - "./build.sh clean test"
before_install:
- lscpu

addons:
  sonarcloud:
    organization: "ironmatt97"
    token:
      secure: "OVXbcBHlj/siOWORCx0n1fDkd+rycH4f6HZIMyPEIcFO0PvWUO68AIBn7E7hMu5cmNc9YJcoZJWpTLd5liZpn1VwTAMvBlf8kV6m6+eYQbyqKR0vG3C/i1Gyiu/BW0xuWgVRsJUuf0jRgMJyGB/47urWIqmrTgQ7EujnrC5NxcN/PpHnNbk6rw6tC7tOO9VrEsLkwhTSwfBQZzhkPEt3oNdqoDRbusLMJlmT7oJtDpBPcDgh/OQFWPCk8Llt5+qX7jATFwTxpBa8ZhTRzyLcirDFOebMPZMjHV1BXmBHSGuUgFD0ZDah6e8bEkEeggN+P5X4PeBaF9OjkrzN6D4mv4FeE4eCDX/bOYdKiP9hLRV4pnMukNbgdyhukyNnhUNRbg+Bp1l1u8+W9tCLIceMrDCVIwIYhCtxUjxC6HsGNGwqYz82mPNRDNFfD6fc3cWrhK/arg9ToF+XFL0aP4VKJcKHqYvz3dDmQYnua/4tqszpXjbtSg5bFnNoadRcpFQLKxnLE/Jg5jc77wWmeuNymXdRCusePHzLvDHvRkoXrb5dGMS4rbCupUf8uTK8mDJnFL5epA9fa+0eB2tNr4uG6+0t1sK8IM9yOGSxfBvAc2pTEOAif2PxDLOqDCeW289KHMiZa8J20eSHizoXXGSXnyWYZpSzlwLbse+iYlvcORs=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=IronMatt97_avro
